### ISSUE TITLE
想参考你的人脸动态贴纸，发现功能不可以用，可以说说方案吗

### ISSUE THREAD

**Issue by qluojieq** [Martin20150405/In77Camera#3]
关键技术人脸特征点定位，我们使用的第三方的；所以现在的难点是怎么去画这个这个动态的贴纸效果，

**Comment by Martin20150405** [comment]
难点在准确实时的人脸关键点定位，动态贴纸就是个OpenGL（或使用游戏引擎如cocos）贴图，可以参考FaceU的素材
