### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by carlos815** [Martin20150405/In77Camera#5]
Hi, I can see that you don´t have a logotype. What do you think about having an image upgrade (A banner for the GitHub project or any other graphics that your app would need).

I can sent you some drafts if you like. I`m thinking about some ideas maybe an obturator with the 77 number along. 

Let me know.

**Comment by Martin20150405** [comment]
Awesome. It's not that important but I will be honored if you could help.

**Comment by Martin20150405** [comment]
I prefer the left one.

**Comment by carlos815** [comment]
Ok, here is the banner for the GitHub Project, I´m uploading the original logo files in my drive (png, jpg and svg), I will send it to you in a few hours. 
![banner github](https://user-images.githubusercontent.com/30379002/45506407-b95fcf80-b754-11e8-8585-26d307085dc7.jpg)

**Comment by carlos815** [comment]
[Original files](https://drive.google.com/open?id=1MYr9RXWkOo7M53jN_jOKWltS_NKS2k6d) In this drive are all the files with diferent sizes and resolutions to be used inside the app. Let me know if you need any other format or resolution.
